### Make sure server is running

GET http://localhost:3000/

### Get all of the list of products

GET http://localhost:3000/product

### Create a new product

POST http://localhost:3000/product
Content-Type: application/json

{
  "product_name": "Dori Sangat Bagus",
  "price": 10000,
  "image_url": "www.samsul.com",
  "categories": "cartoon",
  "rating": 1,
  "quantity":1,
  "description": "This is an apple product",
  "reputation": 800,
  "availability": 1,
  "created_by": "Wisma Chaerul"
}

### Get Product by its ID
GET http://localhost:3000/product/64318f26c3355bfb14648647

### Patch a product 
PATCH http://localhost:3000/product/64319bff267b4ad51ddfb318
Content-Type: application/json

{
    "quantity":15
}

### Delete a product by its ID
DELETE http://localhost:3000/product/64318b7bc3355bfb14648644

